// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEyUO801242hlFoUxTSXBpQuZmjRYHkg8',
    appId: '1:429903194432:web:aff42a596f1bbb8dae72a5',
    messagingSenderId: '429903194432',
    projectId: 'agriculture-signin',
    authDomain: 'agriculture-signin.firebaseapp.com',
    storageBucket: 'agriculture-signin.appspot.com',
    measurementId: 'G-JPW0HP8MRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnGuEf-Y7nQrz9009uX7rkcelBOQazWOc',
    appId: '1:429903194432:android:aaa4ca661d0d0667ae72a5',
    messagingSenderId: '429903194432',
    projectId: 'agriculture-signin',
    storageBucket: 'agriculture-signin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgEX3749M231LotDwJMXDgZ0UgSfqPXAo',
    appId: '1:429903194432:ios:6fa5cf568f31c9ceae72a5',
    messagingSenderId: '429903194432',
    projectId: 'agriculture-signin',
    storageBucket: 'agriculture-signin.appspot.com',
    iosBundleId: 'com.example.agrimap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgEX3749M231LotDwJMXDgZ0UgSfqPXAo',
    appId: '1:429903194432:ios:6fa5cf568f31c9ceae72a5',
    messagingSenderId: '429903194432',
    projectId: 'agriculture-signin',
    storageBucket: 'agriculture-signin.appspot.com',
    iosBundleId: 'com.example.agrimap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEyUO801242hlFoUxTSXBpQuZmjRYHkg8',
    appId: '1:429903194432:web:8b97ed558f131d20ae72a5',
    messagingSenderId: '429903194432',
    projectId: 'agriculture-signin',
    authDomain: 'agriculture-signin.firebaseapp.com',
    storageBucket: 'agriculture-signin.appspot.com',
    measurementId: 'G-H64286Q5VB',
  );
}
